// Dependency-free single-page PDF writer (Helvetica, ASCII text). Used only for the
// demo proposal document when Odoo is not connected.
const esc = (s) => String(s).replace(/[^\x20-\x7E]/g, '-').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')

function buildPdf(items) {
  let y = 800
  const ops = []
  for (const it of items) {
    y -= it.gap ?? it.size * 1.55
    if (!it.text) continue
    const [r, g, b] = it.color || [0.05, 0.1, 0.16]
    ops.push(`${r} ${g} ${b} rg BT /${it.bold ? 'F2' : 'F1'} ${it.size} Tf ${it.x ?? 50} ${y.toFixed(1)} Td (${esc(it.text)}) Tj ET`)
  }
  const stream = ops.join('\n')
  const objs = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
  ]
  let out = '%PDF-1.4\n'
  const offsets = []
  objs.forEach((o, i) => { offsets.push(out.length); out += `${i + 1} 0 obj\n${o}\nendobj\n` })
  const xref = out.length
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`
  offsets.forEach((o) => { out += `${String(o).padStart(10, '0')} 00000 n \n` })
  out += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  return new TextEncoder().encode(out)
}

export function buildProposalPdf(p) {
  const fmt = (n) => `SAR ${Number(n).toLocaleString('en-US')}`
  const items = [
    { text: 'AUDIT ENGAGEMENT PROPOSAL', size: 20, bold: true },
    { text: p.reference, size: 12, color: [0.4, 0.45, 0.5] },
    { text: '', size: 8 },
    { text: 'Prepared for', size: 9, bold: true, color: [0.5, 0.55, 0.6] },
    { text: p.client, size: 14, bold: true },
    { text: `Attention: ${p.contactName} (${p.contactEmail})`, size: 10 },
    ...(p.crNumber ? [{ text: `CR ${p.crNumber}`, size: 10 }] : []),
    ...(p.city ? [{ text: p.city, size: 10 }] : []),
    { text: '', size: 8 },
    { text: 'Engagement', size: 9, bold: true, color: [0.5, 0.55, 0.6] },
    { text: `Auditor: ${p.auditor}`, size: 11 },
    { text: `Audit type: ${p.auditType}`, size: 11 },
    { text: '', size: 8 },
    { text: 'Professional fees', size: 9, bold: true, color: [0.5, 0.55, 0.6] },
    ...p.lines.map((l) => ({ text: `${l.name}  -  ${fmt(l.amount)}`, size: 11 })),
    { text: '', size: 4 },
    { text: `Total: ${fmt(p.total)}`, size: 14, bold: true },
    { text: '', size: 8 },
    { text: `Date: ${p.createdDate}   Valid until: ${p.expiryDate}`, size: 10 },
    { text: `Prepared by: ${p.preparedBy}`, size: 10 },
    { text: '', gap: 40, size: 1 },
    { text: 'DEMO DOCUMENT - Odoo is not connected, so this proposal was not generated by Odoo.', size: 9, bold: true, color: [0.8, 0.2, 0.2] },
  ]
  return buildPdf(items)
}

export function bytesToBase64(bytes) {
  let bin = ''
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  return btoa(bin)
}
