import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { CheckCircle2, FileText, Loader2, X, AlertTriangle } from 'lucide-react'
import { AUDITORS, AUDIT_TYPES, SERVICES, ProposalError, addGeneratedProposal, generateProposal } from '../../utils/proposals'
import { foUser } from '../../data/sampleData'

const STEPS = ['Sending the request to Odoo…', 'Odoo is generating the proposal…', 'Retrieving the proposal PDF…']
const emptyForm = {
  client: '', contactName: '', contactEmail: '', crNumber: '', city: '',
  auditor: '', auditType: '', auditFee: '', services: {},
}
const inputCls = (bad) => `w-full rounded-lg border px-3 py-2 text-sm outline-none focus:border-navy ${bad ? 'border-alert-red' : 'border-slate-300'}`

export default function NewProposalModal({ onClose, onView }) {
  const [form, setForm] = useState(emptyForm)
  const [errors, setErrors] = useState({})
  const [phase, setPhase] = useState('form')
  const [step, setStep] = useState(0)
  const [result, setResult] = useState(null)
  const [failure, setFailure] = useState('')

  useEffect(() => {
    if (phase !== 'working') return undefined
    const t = setInterval(() => setStep((s) => Math.min(s + 1, STEPS.length - 1)), 1800)
    return () => clearInterval(t)
  }, [phase])

  const clearError = (k) => setErrors((e) => (e[k] ? { ...e, [k]: undefined } : e))
  const set = (k) => (e) => { setForm((f) => ({ ...f, [k]: e.target.value })); clearError(k) }
  const toggleService = (key) => { setForm((f) => ({ ...f, services: { ...f.services, [key]: f.services[key] ? null : { fee: '' } } })); clearError(key) }
  const setServiceFee = (key, fee) => { setForm((f) => ({ ...f, services: { ...f.services, [key]: { fee } } })); clearError(key) }

  const total = (Number(form.auditFee) || 0) + SERVICES.reduce((s, x) => s + (form.services[x.key] ? Number(form.services[x.key].fee) || 0 : 0), 0)

  const validate = () => {
    const e = {}
    if (!form.client.trim()) e.client = 'Enter the client name'
    if (!form.contactName.trim()) e.contactName = 'Enter a contact name'
    if (!/^\S+@\S+\.\S+$/.test(form.contactEmail.trim())) e.contactEmail = 'Enter a valid email'
    if (!form.auditor) e.auditor = 'Select the auditor'
    if (!form.auditType) e.auditType = 'Select the audit type'
    if (!(Number(form.auditFee) > 0)) e.auditFee = 'Enter a valid fee'
    SERVICES.forEach((s) => { if (form.services[s.key] && !(Number(form.services[s.key].fee) > 0)) e[s.key] = 'Enter a valid fee' })
    setErrors(e)
    return Object.keys(e).length === 0
  }

  const submit = async () => {
    if (!validate()) return
    setPhase('working'); setStep(0); setFailure('')
    try {
      const record = await generateProposal(
        { ...form, client: form.client.trim(), contactName: form.contactName.trim(), contactEmail: form.contactEmail.trim(), crNumber: form.crNumber.trim(), city: form.city.trim() },
        foUser.name,
      )
      addGeneratedProposal(record)
      setResult(record); setPhase('done')
    } catch (err) {
      setFailure(err instanceof ProposalError ? err.message : 'Could not reach the proposal service. Please try again.')
      setPhase('failed')
    }
  }

  const busy = phase === 'working'
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={(e) => e.target === e.currentTarget && !busy && onClose()}>
      <motion.div
        initial={{ opacity: 0, scale: 0.94 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.94 }}
        role="dialog" aria-label="New proposal" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"
      >
        <div className="mb-5 flex items-center justify-between">
          <div>
            <h3 className="text-sm font-bold text-navy">New Proposal</h3>
            <p className="text-xs text-slate-500">Generated by Odoo and delivered into this platform</p>
          </div>
          {!busy && <button onClick={onClose} aria-label="Close"><X className="h-4 w-4 text-slate-400" /></button>}
        </div>

        {phase === 'form' || phase === 'failed' ? (
          <>
            {phase === 'failed' && (
              <div role="alert" className="mb-4 flex items-start gap-2 rounded-lg border border-alert-red/30 bg-alert-red/5 p-3 text-xs text-alert-red">
                <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" /> <span>{failure}</span>
              </div>
            )}
            <div className="max-h-[62vh] space-y-4 overflow-y-auto pr-1">
              <div>
                <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-client">Client / company name *</label>
                <input id="np-client" value={form.client} onChange={set('client')} className={inputCls(errors.client)} placeholder="e.g. Al-Bashir Trading Co. LLC" />
                {errors.client && <p className="mt-1 text-[10px] text-alert-red">{errors.client}</p>}
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-contact">Contact person *</label>
                  <input id="np-contact" value={form.contactName} onChange={set('contactName')} className={inputCls(errors.contactName)} />
                  {errors.contactName && <p className="mt-1 text-[10px] text-alert-red">{errors.contactName}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-email">Contact email *</label>
                  <input id="np-email" type="email" value={form.contactEmail} onChange={set('contactEmail')} className={inputCls(errors.contactEmail)} />
                  {errors.contactEmail && <p className="mt-1 text-[10px] text-alert-red">{errors.contactEmail}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-cr">CR number</label>
                  <input id="np-cr" value={form.crNumber} onChange={set('crNumber')} className={inputCls(false)} />
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-city">City</label>
                  <input id="np-city" value={form.city} onChange={set('city')} className={inputCls(false)} placeholder="e.g. Riyadh, KSA" />
                </div>
              </div>

              <div>
                <p className="mb-1.5 text-xs font-semibold text-slate-600">Auditor *</p>
                <div className="grid grid-cols-2 gap-2">
                  {AUDITORS.map((a) => (
                    <button key={a} type="button" onClick={() => { setForm((f) => ({ ...f, auditor: a })); clearError('auditor') }}
                      className={`rounded-lg border-2 py-2.5 text-sm font-semibold transition-all ${form.auditor === a ? 'border-navy bg-navy text-white' : 'border-slate-200 text-slate-500 hover:border-slate-300'}`}>{a}</button>
                  ))}
                </div>
                {errors.auditor && <p className="mt-1 text-[10px] text-alert-red">{errors.auditor}</p>}
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-type">Audit type *</label>
                  <select id="np-type" value={form.auditType} onChange={set('auditType')} className={inputCls(errors.auditType)}>
                    <option value="">Select audit type</option>
                    {AUDIT_TYPES.map((t) => <option key={t}>{t}</option>)}
                  </select>
                  {errors.auditType && <p className="mt-1 text-[10px] text-alert-red">{errors.auditType}</p>}
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-semibold text-slate-600" htmlFor="np-fee">Audit fee (SAR) *</label>
                  <input id="np-fee" inputMode="numeric" value={form.auditFee} onChange={set('auditFee')} className={inputCls(errors.auditFee)} placeholder="e.g. 18500" />
                  {errors.auditFee && <p className="mt-1 text-[10px] text-alert-red">{errors.auditFee}</p>}
                </div>
              </div>

              <div>
                <p className="mb-2 text-xs font-semibold text-slate-600">Additional services</p>
                <div className="space-y-2">
                  {SERVICES.map(({ key, label }) => (
                    <div key={key}>
                      <label className="flex cursor-pointer items-center gap-2">
                        <input type="checkbox" checked={!!form.services[key]} onChange={() => toggleService(key)} className="h-4 w-4 rounded accent-navy" />
                        <span className="text-sm text-slate-700">{label}</span>
                      </label>
                      {form.services[key] && (
                        <>
                          <input value={form.services[key].fee} onChange={(e) => setServiceFee(key, e.target.value)} inputMode="numeric"
                            placeholder={`${label} fee (SAR)`} aria-label={`${label} fee`} className={`mt-1.5 ${inputCls(errors[key])}`} />
                          {errors[key] && <p className="mt-1 text-[10px] text-alert-red">{errors[key]}</p>}
                        </>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {total > 0 && (
                <div className="flex items-center justify-between rounded-lg bg-navy/5 px-4 py-2.5">
                  <span className="text-xs font-semibold text-slate-500">Total engagement fee</span>
                  <span className="text-sm font-bold text-navy">SAR {total.toLocaleString()}</span>
                </div>
              )}
            </div>
            <div className="mt-5 flex gap-2">
              <button onClick={onClose} className="flex-1 rounded-lg border border-slate-300 py-2.5 text-sm font-semibold text-navy hover:bg-slate-50">Cancel</button>
              <button onClick={submit} className="flex-1 rounded-lg bg-brand py-2.5 text-sm font-semibold text-white hover:bg-[#D12C35]">
                {phase === 'failed' ? 'Try again' : 'Generate with Odoo'}
              </button>
            </div>
          </>
        ) : null}

        {phase === 'working' && (
          <div className="flex flex-col items-center py-10 text-center" role="status" aria-live="polite">
            <Loader2 className="h-8 w-8 animate-spin text-brand" />
            <AnimatePresence mode="wait">
              <motion.p key={step} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="mt-4 text-sm font-semibold text-navy">
                {STEPS[step]}
              </motion.p>
            </AnimatePresence>
            <p className="mt-1 text-xs text-slate-400">Please keep this window open</p>
          </div>
        )}

        {phase === 'done' && result && (
          <div className="py-4 text-center">
            <CheckCircle2 className="mx-auto h-10 w-10 text-emerald" />
            <p className="mt-3 text-sm font-bold text-navy">Proposal {result.reference} generated</p>
            <p className="mt-1 text-xs text-slate-500">{result.client} · {result.auditor} · SAR {Number(result.fee).toLocaleString()}</p>
            <span className={`mt-3 inline-block rounded-md px-2.5 py-1 text-[11px] font-bold ${result.source === 'odoo' ? 'bg-teal-100 text-teal-700' : 'bg-amber/10 text-amber'}`}>
              {result.source === 'odoo' ? 'Generated by Odoo' : 'Demo document — Odoo not connected'}
            </span>
            {result.pdfError && <p className="mt-3 text-[11px] text-amber">{result.pdfError}</p>}
            <p className="mt-3 text-xs text-slate-500">It is now in your Proposals list awaiting approval.</p>
            <div className="mt-5 flex gap-2">
              <button onClick={onClose} className="flex-1 rounded-lg border border-slate-300 py-2.5 text-sm font-semibold text-navy hover:bg-slate-50">Close</button>
              <button onClick={() => onView(result)} className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-brand py-2.5 text-sm font-semibold text-white hover:bg-[#D12C35]">
                <FileText className="h-4 w-4" /> View Proposal
              </button>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  )
}
